FIELD_ASSESS_RESULT = "privacy_assessment_result"
FIELD_RESOURCE_VISIBLE = "resource_visible"
FIELD_GOVERNANCE_ACKN = "governance_acknowledgement"
FIELD_REQUEST_ASSESS = "request_privacy_assessment"

FIELD_DE_IDENTIFIED = "de_identified_data"
FIELD_NEXT_UPDATE_DUE = "next_update_due"

FALSE = "FALSE"
NO = "NO"
YES = "YES"
EMPTY = "EMPTY"
UPDATED = "UPDATED"

RES_RESTRICTED_FIELDS = [FIELD_ASSESS_RESULT, FIELD_RESOURCE_VISIBLE, FIELD_GOVERNANCE_ACKN, FIELD_REQUEST_ASSESS]
PKG_RESTRICTED_FIELDS = [FIELD_DE_IDENTIFIED, FIELD_NEXT_UPDATE_DUE]

PRIVACY_ASSESS_RESULT_LINK = "ckanext.resource_visibility.assessment_result_help_url"
